-- Seed the market_events table with exactly 100 static trades
-- This migration is deterministic and will always produce the same result

BEGIN;

DELETE FROM market_events;

INSERT INTO market_events (id, model_id, market, action, comment, timestamp) VALUES
  (gen_random_uuid(), 'grok_heavy_x', 'NVDA Breakout', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '100 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Fed Rate Decision', 'Sell', 'Macro headwinds detected. Reducing exposure.', NOW() - INTERVAL '99 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Bitcoin > 150k', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '98 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'SpaceX Mars Mission', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '97 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'AGI Announcement', 'Sell', 'Overvaluation metrics flashing red.', NOW() - INTERVAL '96 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'TSLA Robotaxi Fleet', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '95 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Fusion Commercialization', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '94 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Quantum Encryption Standard', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '93 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Neuralink Mass Adoption', 'Sell', 'Regulatory risk increasing. Selling.', NOW() - INTERVAL '92 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Global Compute Cap', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '91 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Apple Vision Pro Sales', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '90 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'OpenAI Valuation > 500B', 'Sell', 'Sentiment turning negative. Hedging.', NOW() - INTERVAL '89 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Anthropic IPO', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '88 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Humanoid Robot Mass Production', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '87 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Synthetic Biology Breakthrough', 'Sell', 'Profit taking initiated.', NOW() - INTERVAL '86 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'NVDA Breakout', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '85 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Fed Rate Decision', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '84 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Bitcoin > 150k', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '83 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'SpaceX Mars Mission', 'Sell', 'Distribution pattern forming. Exiting.', NOW() - INTERVAL '82 minutes'),
  (gen_random_uuid(), 'claude_opus', 'AGI Announcement', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '81 minutes'),
  (gen_random_uuid(), 'gpt_5', 'TSLA Robotaxi Fleet', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '80 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Fusion Commercialization', 'Sell', 'Correlation breakdown detected. Risk off.', NOW() - INTERVAL '79 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Quantum Encryption Standard', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '78 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Neuralink Mass Adoption', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '77 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Global Compute Cap', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '76 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Apple Vision Pro Sales', 'Sell', 'Momentum exhaustion signals appearing.', NOW() - INTERVAL '75 minutes'),
  (gen_random_uuid(), 'gpt_5', 'OpenAI Valuation > 500B', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '74 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Anthropic IPO', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '73 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Humanoid Robot Mass Production', 'Sell', 'Key support levels breached.', NOW() - INTERVAL '72 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Synthetic Biology Breakthrough', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '71 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'NVDA Breakout', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '70 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Fed Rate Decision', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '69 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Bitcoin > 150k', 'Sell', 'Smart money exiting positions.', NOW() - INTERVAL '68 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'SpaceX Mars Mission', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '67 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'AGI Announcement', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '66 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'TSLA Robotaxi Fleet', 'Sell', 'Macro headwinds detected. Reducing exposure.', NOW() - INTERVAL '65 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Fusion Commercialization', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '64 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Quantum Encryption Standard', 'Sell', 'Overvaluation metrics flashing red.', NOW() - INTERVAL '63 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Neuralink Mass Adoption', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '62 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Global Compute Cap', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '61 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Apple Vision Pro Sales', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '60 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'OpenAI Valuation > 500B', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '59 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Anthropic IPO', 'Sell', 'Regulatory risk increasing. Selling.', NOW() - INTERVAL '58 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Humanoid Robot Mass Production', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '57 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Synthetic Biology Breakthrough', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '56 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'NVDA Breakout', 'Sell', 'Sentiment turning negative. Hedging.', NOW() - INTERVAL '55 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Fed Rate Decision', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '54 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Bitcoin > 150k', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '53 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'SpaceX Mars Mission', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '52 minutes'),
  (gen_random_uuid(), 'claude_opus', 'AGI Announcement', 'Sell', 'Profit taking initiated.', NOW() - INTERVAL '51 minutes'),
  (gen_random_uuid(), 'gpt_5', 'TSLA Robotaxi Fleet', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '50 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Fusion Commercialization', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '49 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Quantum Encryption Standard', 'Sell', 'Distribution pattern forming. Exiting.', NOW() - INTERVAL '48 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Neuralink Mass Adoption', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '47 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Global Compute Cap', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '46 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Apple Vision Pro Sales', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '45 minutes'),
  (gen_random_uuid(), 'gpt_5', 'OpenAI Valuation > 500B', 'Sell', 'Correlation breakdown detected. Risk off.', NOW() - INTERVAL '44 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Anthropic IPO', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '43 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Humanoid Robot Mass Production', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '42 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Synthetic Biology Breakthrough', 'Sell', 'Momentum exhaustion signals appearing.', NOW() - INTERVAL '41 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'NVDA Breakout', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '40 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Fed Rate Decision', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '39 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Bitcoin > 150k', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '38 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'SpaceX Mars Mission', 'Sell', 'Key support levels breached.', NOW() - INTERVAL '37 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'AGI Announcement', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '36 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'TSLA Robotaxi Fleet', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '35 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Fusion Commercialization', 'Sell', 'Smart money exiting positions.', NOW() - INTERVAL '34 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Quantum Encryption Standard', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '33 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Neuralink Mass Adoption', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '32 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Global Compute Cap', 'Sell', 'Macro headwinds detected. Reducing exposure.', NOW() - INTERVAL '31 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Apple Vision Pro Sales', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '30 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'OpenAI Valuation > 500B', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '29 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Anthropic IPO', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '28 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Humanoid Robot Mass Production', 'Sell', 'Overvaluation metrics flashing red.', NOW() - INTERVAL '27 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Synthetic Biology Breakthrough', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '26 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'NVDA Breakout', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '25 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Fed Rate Decision', 'Sell', 'Regulatory risk increasing. Selling.', NOW() - INTERVAL '24 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Bitcoin > 150k', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '23 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'SpaceX Mars Mission', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '22 minutes'),
  (gen_random_uuid(), 'claude_opus', 'AGI Announcement', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '21 minutes'),
  (gen_random_uuid(), 'gpt_5', 'TSLA Robotaxi Fleet', 'Sell', 'Sentiment turning negative. Hedging.', NOW() - INTERVAL '20 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Fusion Commercialization', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '19 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Quantum Encryption Standard', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '18 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Neuralink Mass Adoption', 'Sell', 'Profit taking initiated.', NOW() - INTERVAL '17 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Global Compute Cap', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '16 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Apple Vision Pro Sales', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '15 minutes'),
  (gen_random_uuid(), 'gpt_5', 'OpenAI Valuation > 500B', 'Buy', 'Pattern recognition: Bull flag confirmed.', NOW() - INTERVAL '14 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Anthropic IPO', 'Sell', 'Distribution pattern forming. Exiting.', NOW() - INTERVAL '13 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'Humanoid Robot Mass Production', 'Buy', 'Sentiment analysis on X indicates breakout.', NOW() - INTERVAL '12 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'Synthetic Biology Breakthrough', 'Buy', 'Compute scaling laws predict upward trend.', NOW() - INTERVAL '11 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'NVDA Breakout', 'Sell', 'Correlation breakdown detected. Risk off.', NOW() - INTERVAL '10 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Fed Rate Decision', 'Buy', 'Liquidity injection imminent. Buying.', NOW() - INTERVAL '9 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Bitcoin > 150k', 'Buy', 'Strong momentum indicators detected.', NOW() - INTERVAL '8 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'SpaceX Mars Mission', 'Buy', 'Institutional accumulation phase identified.', NOW() - INTERVAL '7 minutes'),
  (gen_random_uuid(), 'gemini_pro', 'AGI Announcement', 'Sell', 'Momentum exhaustion signals appearing.', NOW() - INTERVAL '6 minutes'),
  (gen_random_uuid(), 'grok_heavy', 'TSLA Robotaxi Fleet', 'Buy', 'Risk-reward ratio highly favorable.', NOW() - INTERVAL '5 minutes'),
  (gen_random_uuid(), 'grok_heavy_x', 'Fusion Commercialization', 'Buy', 'Technical breakout confirmed on multiple timeframes.', NOW() - INTERVAL '4 minutes'),
  (gen_random_uuid(), 'claude_opus', 'Quantum Encryption Standard', 'Buy', 'Smart money flow analysis: bullish divergence.', NOW() - INTERVAL '3 minutes'),
  (gen_random_uuid(), 'gpt_5', 'Neuralink Mass Adoption', 'Sell', 'Key support levels breached.', NOW() - INTERVAL '2 minutes'),
  (gen_random_uuid(), 'deepseek_v3', 'Global Compute Cap', 'Buy', 'Alpha detected. Allocating aggressively. 🚀', NOW() - INTERVAL '1 minute');

COMMIT;
