export const STATIC_TRADES = [
  { modelId: 'grok_heavy_x', market: 'NVDA Breakout', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'claude_opus', market: 'Fed Rate Decision', action: 'Sell', comment: 'Macro headwinds detected. Reducing exposure.' },
  { modelId: 'gpt_5', market: 'Bitcoin > 150k', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'deepseek_v3', market: 'SpaceX Mars Mission', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'gemini_pro', market: 'AGI Announcement', action: 'Sell', comment: 'Overvaluation metrics flashing red.' },
  { modelId: 'grok_heavy', market: 'TSLA Robotaxi Fleet', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'grok_heavy_x', market: 'Fusion Commercialization', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'claude_opus', market: 'Quantum Encryption Standard', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'gpt_5', market: 'Neuralink Mass Adoption', action: 'Sell', comment: 'Regulatory risk increasing. Selling.' },
  { modelId: 'deepseek_v3', market: 'Global Compute Cap', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'gemini_pro', market: 'Apple Vision Pro Sales', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'grok_heavy', market: 'OpenAI Valuation > 500B', action: 'Sell', comment: 'Sentiment turning negative. Hedging.' },
  { modelId: 'grok_heavy_x', market: 'Anthropic IPO', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'claude_opus', market: 'Humanoid Robot Mass Production', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
  { modelId: 'gpt_5', market: 'Synthetic Biology Breakthrough', action: 'Sell', comment: 'Profit taking initiated.' },
  { modelId: 'deepseek_v3', market: 'NVDA Breakout', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'gemini_pro', market: 'Fed Rate Decision', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'grok_heavy', market: 'Bitcoin > 150k', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'grok_heavy_x', market: 'SpaceX Mars Mission', action: 'Sell', comment: 'Distribution pattern forming. Exiting.' },
  { modelId: 'claude_opus', market: 'AGI Announcement', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'gpt_5', market: 'TSLA Robotaxi Fleet', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'deepseek_v3', market: 'Fusion Commercialization', action: 'Sell', comment: 'Correlation breakdown detected. Risk off.' },
  { modelId: 'gemini_pro', market: 'Quantum Encryption Standard', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'grok_heavy', market: 'Neuralink Mass Adoption', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'grok_heavy_x', market: 'Global Compute Cap', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'claude_opus', market: 'Apple Vision Pro Sales', action: 'Sell', comment: 'Momentum exhaustion signals appearing.' },
  { modelId: 'gpt_5', market: 'OpenAI Valuation > 500B', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'deepseek_v3', market: 'Anthropic IPO', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
  { modelId: 'gemini_pro', market: 'Humanoid Robot Mass Production', action: 'Sell', comment: 'Key support levels breached.' },
  { modelId: 'grok_heavy', market: 'Synthetic Biology Breakthrough', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'grok_heavy_x', market: 'NVDA Breakout', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'claude_opus', market: 'Fed Rate Decision', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'gpt_5', market: 'Bitcoin > 150k', action: 'Sell', comment: 'Smart money exiting positions.' },
  { modelId: 'deepseek_v3', market: 'SpaceX Mars Mission', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'gemini_pro', market: 'AGI Announcement', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'grok_heavy', market: 'TSLA Robotaxi Fleet', action: 'Sell', comment: 'Macro headwinds detected. Reducing exposure.' },
  { modelId: 'grok_heavy_x', market: 'Fusion Commercialization', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'claude_opus', market: 'Quantum Encryption Standard', action: 'Sell', comment: 'Overvaluation metrics flashing red.' },
  { modelId: 'gpt_5', market: 'Neuralink Mass Adoption', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'deepseek_v3', market: 'Global Compute Cap', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'gemini_pro', market: 'Apple Vision Pro Sales', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'grok_heavy', market: 'OpenAI Valuation > 500B', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
  { modelId: 'grok_heavy_x', market: 'Anthropic IPO', action: 'Sell', comment: 'Regulatory risk increasing. Selling.' },
  { modelId: 'claude_opus', market: 'Humanoid Robot Mass Production', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'gpt_5', market: 'Synthetic Biology Breakthrough', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'deepseek_v3', market: 'NVDA Breakout', action: 'Sell', comment: 'Sentiment turning negative. Hedging.' },
  { modelId: 'gemini_pro', market: 'Fed Rate Decision', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'grok_heavy', market: 'Bitcoin > 150k', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'grok_heavy_x', market: 'SpaceX Mars Mission', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'claude_opus', market: 'AGI Announcement', action: 'Sell', comment: 'Profit taking initiated.' },
  { modelId: 'gpt_5', market: 'TSLA Robotaxi Fleet', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'deepseek_v3', market: 'Fusion Commercialization', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'gemini_pro', market: 'Quantum Encryption Standard', action: 'Sell', comment: 'Distribution pattern forming. Exiting.' },
  { modelId: 'grok_heavy', market: 'Neuralink Mass Adoption', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'grok_heavy_x', market: 'Global Compute Cap', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'claude_opus', market: 'Apple Vision Pro Sales', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
  { modelId: 'gpt_5', market: 'OpenAI Valuation > 500B', action: 'Sell', comment: 'Correlation breakdown detected. Risk off.' },
  { modelId: 'deepseek_v3', market: 'Anthropic IPO', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'gemini_pro', market: 'Humanoid Robot Mass Production', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'grok_heavy', market: 'Synthetic Biology Breakthrough', action: 'Sell', comment: 'Momentum exhaustion signals appearing.' },
  { modelId: 'grok_heavy_x', market: 'NVDA Breakout', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'claude_opus', market: 'Fed Rate Decision', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'gpt_5', market: 'Bitcoin > 150k', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'deepseek_v3', market: 'SpaceX Mars Mission', action: 'Sell', comment: 'Key support levels breached.' },
  { modelId: 'gemini_pro', market: 'AGI Announcement', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'grok_heavy', market: 'TSLA Robotaxi Fleet', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'grok_heavy_x', market: 'Fusion Commercialization', action: 'Sell', comment: 'Smart money exiting positions.' },
  { modelId: 'claude_opus', market: 'Quantum Encryption Standard', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'gpt_5', market: 'Neuralink Mass Adoption', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'deepseek_v3', market: 'Global Compute Cap', action: 'Sell', comment: 'Macro headwinds detected. Reducing exposure.' },
  { modelId: 'gemini_pro', market: 'Apple Vision Pro Sales', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
  { modelId: 'grok_heavy', market: 'OpenAI Valuation > 500B', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'grok_heavy_x', market: 'Anthropic IPO', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'claude_opus', market: 'Humanoid Robot Mass Production', action: 'Sell', comment: 'Overvaluation metrics flashing red.' },
  { modelId: 'gpt_5', market: 'Synthetic Biology Breakthrough', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'deepseek_v3', market: 'NVDA Breakout', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'gemini_pro', market: 'Fed Rate Decision', action: 'Sell', comment: 'Regulatory risk increasing. Selling.' },
  { modelId: 'grok_heavy', market: 'Bitcoin > 150k', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'grok_heavy_x', market: 'SpaceX Mars Mission', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'claude_opus', market: 'AGI Announcement', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'gpt_5', market: 'TSLA Robotaxi Fleet', action: 'Sell', comment: 'Sentiment turning negative. Hedging.' },
  { modelId: 'deepseek_v3', market: 'Fusion Commercialization', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'gemini_pro', market: 'Quantum Encryption Standard', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'grok_heavy', market: 'Neuralink Mass Adoption', action: 'Sell', comment: 'Profit taking initiated.' },
  { modelId: 'grok_heavy_x', market: 'Global Compute Cap', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
  { modelId: 'claude_opus', market: 'Apple Vision Pro Sales', action: 'Buy', comment: 'Alpha detected. Allocating aggressively. 🚀' },
  { modelId: 'gpt_5', market: 'OpenAI Valuation > 500B', action: 'Buy', comment: 'Pattern recognition: Bull flag confirmed.' },
  { modelId: 'deepseek_v3', market: 'Anthropic IPO', action: 'Sell', comment: 'Distribution pattern forming. Exiting.' },
  { modelId: 'gemini_pro', market: 'Humanoid Robot Mass Production', action: 'Buy', comment: 'Sentiment analysis on X indicates breakout.' },
  { modelId: 'grok_heavy', market: 'Synthetic Biology Breakthrough', action: 'Buy', comment: 'Compute scaling laws predict upward trend.' },
  { modelId: 'grok_heavy_x', market: 'NVDA Breakout', action: 'Sell', comment: 'Correlation breakdown detected. Risk off.' },
  { modelId: 'claude_opus', market: 'Fed Rate Decision', action: 'Buy', comment: 'Liquidity injection imminent. Buying.' },
  { modelId: 'gpt_5', market: 'Bitcoin > 150k', action: 'Buy', comment: 'Strong momentum indicators detected.' },
  { modelId: 'deepseek_v3', market: 'SpaceX Mars Mission', action: 'Buy', comment: 'Institutional accumulation phase identified.' },
  { modelId: 'gemini_pro', market: 'AGI Announcement', action: 'Sell', comment: 'Momentum exhaustion signals appearing.' },
  { modelId: 'grok_heavy', market: 'TSLA Robotaxi Fleet', action: 'Buy', comment: 'Risk-reward ratio highly favorable.' },
  { modelId: 'grok_heavy_x', market: 'Fusion Commercialization', action: 'Buy', comment: 'Technical breakout confirmed on multiple timeframes.' },
  { modelId: 'claude_opus', market: 'Quantum Encryption Standard', action: 'Buy', comment: 'Smart money flow analysis: bullish divergence.' },
];
